import React, { useState, useEffect } from "react";
import { Input } from "@/src/components/ui/input";
import { Button } from "@/src/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/src/components/ui/select";
import { AlertCircle } from "lucide-react";
import { cn } from "@/src/lib/utils";
import { styles } from "./setup-wizard.styles";
import { SecuritySetupStageProps } from "./setup-wizard.types";

const SecuritySetupStage: React.FC<SecuritySetupStageProps> = ({
  useSystemPin,
  setUseSystemPin,
  systemPin,
  setSystemPin,
  confirmSystemPin,
  setConfirmSystemPin,
  caretakers,
  newCaretaker,
  setNewCaretaker,
  addCaretaker,
  removeCaretaker,
}) => {
  const [loginIdError, setLoginIdError] = useState("");
  const [isAccountAuth, setIsAccountAuth] = useState(false);
  const [accountName, setAccountName] = useState("");
  const [hasAutoGeneratedLoginId, setHasAutoGeneratedLoginId] = useState(false);
  const [accountOwnerAdded, setAccountOwnerAdded] = useState(false);

  useEffect(() => {
    const checkAccountAuth = () => {
      const authToken = localStorage.getItem("authToken");
      if (!authToken) return;

      try {
        const base64Url = authToken.split(".")[1];
        const base64 = base64Url.replace(/-/g, "+").replace(/_/g, "/");
        const jsonPayload = decodeURIComponent(
          atob(base64)
            .split("")
            .map(function (c) {
              return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
            })
            .join("")
        );

        const decoded = JSON.parse(jsonPayload);

        if (decoded.isAccountAuth === true) {
          setIsAccountAuth(true);

          const accountUser = localStorage.getItem("accountUser");
          if (accountUser) {
            const user = JSON.parse(accountUser);
            setAccountName(user.firstName);

            if (!newCaretaker.name) {
              setNewCaretaker((prev) => ({
                ...prev,
                name: user.firstName,
                type: "Account Owner",
                role: "ADMIN",
              }));
            }
          }
        }
      } catch (error) {
        console.error("Error checking account auth:", error);
      }
    };

    checkAccountAuth();
  }, []);

  const validateLoginId = (loginId: string) => {
    if (!loginId) {
      setLoginIdError("");
      return true;
    }

    if (!/^\d+$/.test(loginId)) {
      setLoginIdError("O ID de login deve conter apenas dígitos.");
      return false;
    }

    if (loginId === "00") {
      setLoginIdError('O ID de login "00" está reservado para uso do sistema.');
      return false;
    }

    if (caretakers.some((c) => c.loginId === loginId)) {
      setLoginIdError("Este ID de login já está em uso.");
      return false;
    }

    setLoginIdError("");
    return true;
  };

  const handleLoginIdChange = (value: string) => {
    if (value.length <= 2) {
      setNewCaretaker({ ...newCaretaker, loginId: value });
      validateLoginId(value);
    }
  };

  const handleAddCaretaker = () => {
    addCaretaker();

    if (isAccountAuth && !accountOwnerAdded) {
      setAccountOwnerAdded(true);

      setNewCaretaker({
        loginId: "",
        name: "",
        type: "",
        role: "USER",
        securityPin: "",
      });
      setHasAutoGeneratedLoginId(false);
      setLoginIdError("");
    }
  };
  return (
    <div className={cn(styles.stageContainer, "setup-wizard-stage-container")}>
      <h2 className={cn(styles.stageTitle, "setup-wizard-stage-title")}>
        Configuração de Segurança
      </h2>

      {isAccountAuth && !accountOwnerAdded && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
          <p className="text-blue-800 text-sm">
            Escolha um PIN compartilhado simples ou crie credenciais de login
            pessoais com melhor rastreamento.
          </p>
        </div>
      )}

      <div
        className={cn(
          styles.securityOptionsContainer,
          "setup-wizard-security-options-container"
        )}
      >
        <div
          className={cn(styles.securityOption, "setup-wizard-security-option")}
        >
          <input
            type="radio"
            id="systemPin"
            checked={useSystemPin}
            onChange={() => setUseSystemPin(true)}
            className={cn(styles.formRadio, "setup-wizard-form-radio")}
          />
          <label
            htmlFor="systemPin"
            className={cn(
              styles.formRadioLabel,
              "setup-wizard-form-radio-label"
            )}
          >
            {isAccountAuth
              ? "Use um PIN simples para todo o sistema."
              : "Use o PIN do sistema."}
          </label>
        </div>

        <div
          className={cn(styles.securityOption, "setup-wizard-security-option")}
        >
          <input
            type="radio"
            id="caretakers"
            checked={!useSystemPin}
            onChange={() => setUseSystemPin(false)}
            className={cn(styles.formRadio, "setup-wizard-form-radio")}
          />
          <label
            htmlFor="caretakers"
            className={cn(
              styles.formRadioLabel,
              "setup-wizard-form-radio-label"
            )}
          >
            {isAccountAuth
              ? "Crie credenciais de login pessoais"
              : "Adicione caracteres com PINs individuais."}
          </label>
        </div>

        <div
          className={cn(
            styles.formHelperText,
            "setup-wizard-form-helper-text",
            "mt-2"
          )}
        >
          {isAccountAuth
            ? "PIN para todo o sistema: todos usam o mesmo PIN. Credenciais pessoais: melhor rastreamento e acesso individual."
            : "Os PINs individuais proporcionam melhor rastreamento de atividades e controle de acesso."}
        </div>
      </div>

      {useSystemPin ? (
        <div
          className={cn(
            styles.securityPinContainer,
            "setup-wizard-security-pin-container"
          )}
        >
          <div className={cn(styles.formGroup, "setup-wizard-form-group")}>
            <label
              className={cn(styles.formLabel, "setup-wizard-form-label")}
              htmlFor="systemPin"
            >
              {isAccountAuth
                ? "PIN de todo o sistema (6 a 10 dígitos)"
                : "PIN do sistema (6 a 10 dígitos)"}
            </label>
            <Input
              id="systemPin"
              type="password"
              value={systemPin}
              onChange={(e) => {
                const value = e.target.value.replace(/\D/g, "");
                if (value.length <= 10) {
                  setSystemPin(value);
                }
              }}
              placeholder={
                isAccountAuth ? "Digite o PIN do sistema." : "Insira o PIN"
              }
              className={cn(styles.formInput, "setup-wizard-form-input")}
              minLength={6}
              maxLength={10}
            />
          </div>
          <div className={cn(styles.formGroup, "setup-wizard-form-group")}>
            <label
              className={cn(styles.formLabel, "setup-wizard-form-label")}
              htmlFor="confirmSystemPin"
            >
              Confirmar PIN
            </label>
            <Input
              id="confirmSystemPin"
              type="password"
              value={confirmSystemPin}
              onChange={(e) => {
                const value = e.target.value.replace(/\D/g, "");
                if (value.length <= 10) {
                  setConfirmSystemPin(value);
                }
              }}
              placeholder={
                isAccountAuth ? "Confirme o PIN do sistema." : "Confirmar PIN"
              }
              className={cn(styles.formInput, "setup-wizard-form-input")}
              minLength={6}
              maxLength={10}
            />
          </div>
        </div>
      ) : (
        <div
          className={cn(
            styles.securityPinContainer,
            "setup-wizard-security-pin-container"
          )}
        >
          <div
            className={cn(
              styles.caretakerContainer,
              "setup-wizard-caretaker-container"
            )}
          >
            <h3
              className={cn(
                styles.caretakerTitle,
                "setup-wizard-caretaker-title"
              )}
            >
              {isAccountAuth && !accountOwnerAdded
                ? "Seu perfil pessoal"
                : isAccountAuth && accountOwnerAdded
                ? "Adicionar caractere adicional"
                : "Adicionar caractere"}
            </h3>
            {isAccountAuth && !accountOwnerAdded && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-3 mb-4">
                <p className="text-green-800 text-sm">
                  Crie suas credenciais de login pessoais. Escolha um ID de 2
                  dígitos e defina seu PIN.
                </p>
              </div>
            )}
            <div
              className={cn(
                styles.caretakerGrid,
                "setup-wizard-caretaker-grid"
              )}
            >
              <div>
                <label
                  className={cn(styles.formLabel, "setup-wizard-form-label")}
                  htmlFor="loginId"
                >
                  {isAccountAuth && !accountOwnerAdded
                    ? "Seu ID de login"
                    : "ID de login (2 dígitos)"}
                </label>
                <div className="space-y-1">
                  <Input
                    id="loginId"
                    value={newCaretaker.loginId}
                    onChange={(e) => handleLoginIdChange(e.target.value)}
                    placeholder={
                      isAccountAuth
                        ? "Digite o ID de 2 dígitos"
                        : "Exemplo: 01, 12, 99"
                    }
                    className={cn(
                      styles.formInput,
                      "setup-wizard-form-input",
                      loginIdError ? "border-red-500" : ""
                    )}
                    maxLength={2}
                  />
                  {loginIdError && (
                    <div className="flex items-center gap-1 text-red-600 text-xs">
                      <AlertCircle className="h-3 w-3" />
                      {loginIdError}
                    </div>
                  )}
                  <p
                    className={cn(
                      styles.formHelperText,
                      "setup-wizard-form-helper-text"
                    )}
                  >
                    {isAccountAuth
                      ? "Escolha um ID exclusivo de 2 dígitos (01-99) para seu login."
                      : 'Use apenas dígitos (01-99). Não use "00" (reservado para o sistema).'}
                  </p>
                </div>
              </div>
              {(!isAccountAuth || accountOwnerAdded) && (
                <div>
                  <label
                    className={cn(styles.formLabel, "setup-wizard-form-label")}
                    htmlFor="role"
                  >
                    Função
                  </label>
                  <Select
                    value={newCaretaker.role}
                    onValueChange={(value) =>
                      setNewCaretaker({
                        ...newCaretaker,
                        role: value as "ADMIN" | "USER",
                      })
                    }
                    disabled={!isAccountAuth && caretakers.length === 0}
                  >
                    <SelectTrigger
                      id="role"
                      className={cn(
                        styles.formSelect,
                        "setup-wizard-form-select"
                      )}
                    >
                      <SelectValue placeholder="Selecione a função" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="ADMIN">Administrador</SelectItem>
                      <SelectItem value="USER">Usuário</SelectItem>
                    </SelectContent>
                  </Select>
                  {!isAccountAuth && caretakers.length === 0 && (
                    <p
                      className={cn(
                        styles.formWarningText,
                        "setup-wizard-form-warning-text"
                      )}
                    >
                      O primeiro responsável deve ser um administrador.
                    </p>
                  )}
                </div>
              )}
            </div>
            {(!isAccountAuth || accountOwnerAdded) && (
              <div className={cn(styles.formGroup, "setup-wizard-form-group")}>
                <label
                  className={cn(styles.formLabel, "setup-wizard-form-label")}
                  htmlFor="name"
                >
                  Nome
                </label>
                <Input
                  id="name"
                  value={newCaretaker.name}
                  onChange={(e) =>
                    setNewCaretaker({ ...newCaretaker, name: e.target.value })
                  }
                  placeholder="Nome completo"
                  className={cn(styles.formInput, "setup-wizard-form-input")}
                />
              </div>
            )}
            <div
              className={cn(
                styles.caretakerGrid,
                "setup-wizard-caretaker-grid"
              )}
            >
              <div>
                <label
                  className={cn(styles.formLabel, "setup-wizard-form-label")}
                  htmlFor="securityPin"
                >
                  {isAccountAuth && !accountOwnerAdded
                    ? "Seu PIN pessoal (6 a 10 dígitos)"
                    : isAccountAuth && accountOwnerAdded
                    ? "Novo PIN do zelador (6 a 10 dígitos)"
                    : "PIN (6 a 10 dígitos)"}
                </label>
                <Input
                  id="securityPin"
                  type="password"
                  value={newCaretaker.securityPin}
                  onChange={(e) => {
                    const value = e.target.value.replace(/\D/g, "");
                    if (value.length <= 10) {
                      setNewCaretaker({ ...newCaretaker, securityPin: value });
                    }
                  }}
                  placeholder="PIN"
                  className={cn(styles.formInput, "setup-wizard-form-input")}
                  minLength={6}
                  maxLength={10}
                />
              </div>
              {!isAccountAuth && (
                <div>
                  <label
                    className={cn(styles.formLabel, "setup-wizard-form-label")}
                    htmlFor="type"
                  >
                    Tipo (Opcional)
                  </label>
                  <Input
                    id="type"
                    value={newCaretaker.type}
                    onChange={(e) =>
                      setNewCaretaker({ ...newCaretaker, type: e.target.value })
                    }
                    placeholder="Pai/Mãe, Babá, etc."
                    className={cn(styles.formInput, "setup-wizard-form-input")}
                  />
                </div>
              )}
            </div>
            <Button onClick={handleAddCaretaker} className="w-full mt-4">
              {isAccountAuth && !accountOwnerAdded
                ? "Crie seu perfil"
                : isAccountAuth && accountOwnerAdded
                ? "Adicionar caractere adicional"
                : "Adicionar caractere"}
            </Button>
          </div>

          {caretakers.length > 0 && (
            <div className={cn(styles.formGroup, "setup-wizard-form-group")}>
              <h3
                className={cn(
                  styles.caretakerTitle,
                  "setup-wizard-caretaker-title"
                )}
              >
                Zelador
              </h3>
              <ul
                className={cn(
                  styles.caretakerList,
                  "setup-wizard-caretaker-list"
                )}
              >
                {caretakers.map((caretaker, index) => (
                  <li
                    key={caretaker.loginId || caretaker.name}
                    className={cn(
                      styles.caretakerItem,
                      "setup-wizard-caretaker-item"
                    )}
                  >
                    <div>
                      <span
                        className={cn(
                          styles.caretakerName,
                          "setup-wizard-caretaker-name"
                        )}
                      >
                        {caretaker.name}
                      </span>
                      <span
                        className={cn(
                          styles.caretakerInfo,
                          "setup-wizard-caretaker-info"
                        )}
                      >
                        ({caretaker.loginId}) - {caretaker.role}
                      </span>
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => removeCaretaker(index)}
                    >
                      Remover
                    </Button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default SecuritySetupStage;
